[package]
name = "threadspace-memory"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
rusqlite = { version = "0.31", features = ["bundled"] }
serde = { version = "1", features = ["derive"] }